//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public int Id { get; set; }
        public Nullable<int> Marque { get; set; }
        public string Model_ { get; set; }
        public string Annee { get; set; }
        public Nullable<int> Puissance { get; set; }
        public Nullable<float> Reservoir { get; set; }
        public Nullable<int> BoiteVitesse { get; set; }
        public Nullable<float> FreinageUrgence { get; set; }
        public Nullable<float> VitesseMax { get; set; }
        public Nullable<float> Poix { get; set; }
        public Nullable<float> Prix { get; set; }
        public Nullable<int> Autonomie { get; set; }
        public Nullable<float> Cons_Ville { get; set; }
        public Nullable<float> Cons_Route { get; set; }
        public Nullable<float> Cons_Autoroute { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> Carburant { get; set; }
        public Nullable<int> Transmission { get; set; }
        public Nullable<int> PayFabrication { get; set; }
    
        public virtual Carburant Carburant_ { get; set; }
        public virtual Marque Marque_ { get; set; }
        public virtual Pays Pays { get; set; }
        public virtual Transmission Transmission_ { get; set; }
    }
}
