//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoom.Data.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Models
    {
        public int ModelId { get; set; }
        public string Name { get; set; }
        public string Annee { get; set; }
        public int? Puissance { get; set; }
        public float? Reservoir { get; set; }
        public int? BoiteVitesse { get; set; }
        public float? FreinageUrgence { get; set; }
        public float? VitesseMax { get; set; }
        public float? Poix { get; set; }
        public float? Prix { get; set; }
        public int? Autonomie { get; set; }
        public float? ConsVille { get; set; }
        public float? ConsRoute { get; set; }
        public float? ConsAutoroute { get; set; }
        public int? Cc { get; set; }
        public int? MarqueId { get; set; }
        public int? CarburantId { get; set; }
        public int? TransmissionId { get; set; }
        public int? TypeVoitureId { get; set; }
        public string PayFabrication { get; set; }

        public Carburant Carburant { get; set; }
        public Marque Marque { get; set; }
        public Pays PayFabricationNavigation { get; set; }
        public Transmission Transmission { get; set; }
        public TypeVoiture TypeVoiture { get; set; }
    }
}
