//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoom.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transmission
    {
        public Transmission()
        {
            Models = new HashSet<Models>();
        }

        public int TransmissionId { get; set; }
        public string Name { get; set; }

        public ICollection<Models> Models { get; set; }
    }
}
