//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoom.Data.Model
{   using System;
    using System.Collections.Generic;
    
    public partial class TypeVoiture
    {
        public TypeVoiture()
        {
            Models = new HashSet<Models>();
        }

        public int TypeVoitureId { get; set; }
        public string Type { get; set; }

        public ICollection<Models> Models { get; set; }
    }
}
