//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoom.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carburant> Carburant { get; set; }
        public virtual DbSet<Marque> Marque { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<Transmission> Transmission { get; set; }
        public virtual DbSet<TypeVoiture> TypeVoiture { get; set; }
    }
}
