//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShowRoom.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pays
    {
        public int PaysId { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }

        public virtual ICollection<Model> Model { get; set; }
    }
}
